### ISSUE TITLE
`FreestyleJobTest#should_visit_build_with_permalink` fails on 2.453+

### ISSUE THREAD

**Issue by basil** [jenkinsci/acceptance-test-harness#1544]
Starting with https://github.com/jenkinsci/jenkins/pull/8110 by @janfaracik in 2.453, `FreestyleJobTest#should_visit_build_with_permalink` fails with

```
java.lang.AssertionError: 
Build has no changes
Expected: Text matching \QNo changes\E
     but: was "http://127.0.0.1:43213/job/indigenous_warning/lastBuild/"
"1\n2\nDashboard\nindigenous_warning\n#1\nStatus\nChanges\nConsole Output\nEdit Build Information\nDelete build ‘#1’\nKeep this build forever\nStarted 0.8 sec ago\nTook 18 ms\nSuccess\n#1 (May 14, 2024, 3:42:14 PM)\nAdd description\nStarted by anonymous user\nREST API\nJenkins 2.458"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at core.FreestyleJobTest.should_visit_build_with_permalink(FreestyleJobTest.java:103)
```

This looks like a legitimate regression, tracked in core as [JENKINS-73168](https://issues.jenkins.io/browse/JENKINS-73168).

**Comment by basil** [comment]
I have added a workaround in #1545. #1548 tracks the removal of this workaround as part of fixing [JENKINS-73168](https://issues.jenkins.io/browse/JENKINS-73168).
