### ISSUE TITLE
Version 3.0 of Matrix Authorization Strategy breaks acceptance-test-harness

### ISSUE THREAD

**Issue by dkjellin** [jenkinsci/acceptance-test-harness#721]
Latest version (3.0) of Matrix Authorization Strategy splits from one button "Add user or group" to two buttons "Add user" and "Add group" respectively. This breaks the selector in org.jenkinsci.test.acceptance.plugins.matrix_auth.MatrixAuthorizationStrategy

### Version report

Jenkins and plugins versions report: Matrix Authorization Strategy version 3, Jenkins 2.289.1 and later

Because the selector is broken tests that rely on it are now failing with a stack trace like: (snipped as it is quite a long stack trace)

>*** Element info: {Using=xpath, value=.//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Add user or group…' or ./@name = 'Add user or group…' or contains(./@value, 'Add user or group…')) or contains(./@title, 'Add user or group…'))] | .//input[./@type = 'image'][contains(./@alt, 'Add user or group…')] | .//button[(((./@id = 'Add user or group…' or contains(./@value, 'Add user or group…')) or contains(normalize-space(.), 'Add user or group…')) or contains(./@title, 'Add user or group…'))] | .//input[./@type = 'image'][contains(./@alt, 'Add user or group…')]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:185)
	at org.openqa.selenium.remote.RemoteWebElement.findElementByXPath(RemoteWebElement.java:261)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:404)
	at com.sun.proxy.$Proxy41.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.findElement(EventFiringWebDriver.java:496)
	at org.jenkinsci.test.acceptance.plugins.matrix_auth.MatrixAuthorizationStrategy.lambda$addUser$0(MatrixAuthorizationStrategy.java:23)
	at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.runThenHandleAlert(CapybaraPortingLayerImpl.java:385)
	at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.runThenHandleAlert(CapybaraPortingLayerImpl.java:379)
	at org.jenkinsci.test.acceptance.plugins.matrix_auth.MatrixAuthorizationStrategy.addUser(MatrixAuthorizationStrategy.java:23)

**Comment by timja** [comment]
FYI @daniel-beck in case you have time

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/acceptance-test-harness/pull/720

https://github.com/jenkinsci/acceptance-test-harness/releases/tag/acceptance-test-harness-1.109
