### ISSUE TITLE
WorkflowPluginTest#linearFlow is flakey

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#727]
In:

- https://github.com/jenkinsci/acceptance-test-harness/pull/723
- https://github.com/jenkinsci/acceptance-test-harness/pull/726
- https://github.com/jenkinsci/acceptance-test-harness/pull/728

https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-726/1/pipeline

```
master60361|2021-12-24 09:59:11.449+0000 [id=82]	INFO	hudson.slaves.CommandLauncher#launch: agent launched for organic_salad
master60361|2021-12-24 09:59:12.386+0000 [id=115]	WARNING	o.e.j.s.h.ContextHandler$Context#log: Error while serving http://127.0.0.1:60361/job/digital_comfort/1/input/30df4afa64a9373296bec35feb317cee/proceedEmpty
master60361|java.lang.NullPointerException
master60361|	at org.jenkinsci.plugins.workflow.support.steps.input.InputStepExecution.canSettle(InputStepExecution.java:305)
master60361|	at org.jenkinsci.plugins.workflow.support.steps.input.InputStepExecution.canSubmit(InputStepExecution.java:296)
master60361|	at org.jenkinsci.plugins.workflow.support.steps.input.InputStepExecution.preSubmissionCheck(InputStepExecution.java:262)
master60361|	at org.jenkinsci.plugins.workflow.support.steps.input.InputStepExecution.doProceedEmpty(InputStepExecution.java:219)
master60361|	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
master60361|	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:398)
master60361|Caused: java.lang.reflect.InvocationTargetException
master60361|	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:402)
master60361|	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:410)
master60361|	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:78)
master60361|	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
master60361|	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:208)
master60361|	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:141)
master60361|	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)
master60361|	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
master60361|	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
master60361|	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
master60361|	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
master60361|	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
master60361|	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
master60361|	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
master60361|	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
master60361|	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
master60361|	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
master60361|	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
```

cc @car-roll @jglick

**Comment by jglick** [comment]
Not sure what the root cause is, but https://github.com/jenkinsci/pipeline-input-step-plugin/pull/69 would at a minimum change the error.
