### ISSUE TITLE
ATH always installs form-element-path plugin which causes failures due to detached plugins

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/acceptance-test-harness#775]
### Jenkins and plugins versions report

the ATH tests start by installing  `form-element-path.jpi`

as this is not built with the weekly (or last LTS) this often causes detached plugins to be installed at their bundled versions.

Then when any test requires a plugin that depends on a newer version of these detached plugins the test blows up.

e.g. https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-772/2/testReport/junit/plugins/OwnershipPluginTest/java_11_jenkins_latest_split7___explicitly_set_ownership/ 

```
Installing form-element-path.jpi
master00000|Running from: /home/jenkins/workspace/e_acceptance-test-harness_PR-772/jenkins-latest.war
...snip...
master00000|2022-05-18 13:56:59.254+0000 [id=48]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /home/jenkins/workspace/e_acceptance-test-harness_PR-772/target/jenkins7533342259552178954home/plugins/javax-activation-api.jpi
master00000|2022-05-18 13:56:59.284+0000 [id=48]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /home/jenkins/workspace/e_acceptance-test-harness_PR-772/target/jenkins7533342259552178954home/plugins/javax-mail-api.jpi
...snip...
master00000|2022-05-18 13:57:15.876+0000 [id=22]	INFO	hudson.PluginManager#install: Starting installation of a batch of 2 plugins plus their dependencies
master00000|2022-05-18 13:57:15.877+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of apache-httpcomponents-client-4-api for plugin ownership
master00000|2022-05-18 13:57:15.878+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of jaxb for plugin apache-httpcomponents-client-4-api
master00000|2022-05-18 13:57:15.878+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of javax-activation-api for plugin jaxb
master00000|2022-05-18 13:57:15.880+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of sshd for plugin jaxb
master00000|2022-05-18 13:57:15.880+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of jdk-tool for plugin apache-httpcomponents-client-4-api
master00000|2022-05-18 13:57:15.881+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of trilead-api for plugin jdk-tool
master00000|2022-05-18 13:57:15.881+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of command-launcher for plugin apache-httpcomponents-client-4-api
master00000|2022-05-18 13:57:15.881+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of script-security for plugin command-launcher
master00000|2022-05-18 13:57:15.881+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of caffeine-api for plugin script-security
master00000|2022-05-18 13:57:15.882+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of workflow-cps for plugin ownership
master00000|2022-05-18 13:57:15.882+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of ace-editor for plugin workflow-cps
master00000|2022-05-18 13:57:15.882+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of bouncycastle-api for plugin ace-editor
master00000|2022-05-18 13:57:15.882+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of workflow-scm-step for plugin workflow-cps
master00000|2022-05-18 13:57:15.883+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of workflow-step-api for plugin workflow-scm-step
master00000|2022-05-18 13:57:15.883+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of structs for plugin workflow-step-api
master00000|2022-05-18 13:57:15.883+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of scm-api for plugin workflow-cps
master00000|2022-05-18 13:57:15.883+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of workflow-support for plugin workflow-cps
master00000|2022-05-18 13:57:15.884+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of workflow-api for plugin workflow-support
master00000|2022-05-18 13:57:15.884+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of mailer for plugin ownership
master00000|2022-05-18 13:57:15.884+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of display-url-api for plugin mailer
master00000|2022-05-18 13:57:15.884+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of matrix-auth for plugin ownership
master00000|2022-05-18 13:57:15.885+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of matrix-project for plugin ownership
master00000|2022-05-18 13:57:15.885+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of junit for plugin matrix-project
master00000|2022-05-18 13:57:15.885+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of jackson2-api for plugin junit
master00000|2022-05-18 13:57:15.885+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of snakeyaml-api for plugin jackson2-api
master00000|2022-05-18 13:57:15.886+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of bootstrap5-api for plugin junit
master00000|2022-05-18 13:57:15.886+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of font-awesome-api for plugin bootstrap5-api
master00000|2022-05-18 13:57:15.886+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of plugin-util-api for plugin font-awesome-api
master00000|2022-05-18 13:57:15.886+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of popper2-api for plugin bootstrap5-api
master00000|2022-05-18 13:57:15.887+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of echarts-api for plugin junit
master00000|2022-05-18 13:57:15.887+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of jquery3-api for plugin echarts-api
master00000|2022-05-18 13:57:15.887+0000 [id=22]	INFO	hudson.model.UpdateSite$Plugin#deploy: Adding dependent install of checks-api for plugin junit
master00000|2022-05-18 13:57:15.931+0000 [id=114]	INFO	h.model.UpdateCenter$DownloadJob#run: Starting the installation of javax-activation-api on behalf of anonymous
master00000|2022-05-18 13:57:15.932+0000 [id=114]	INFO	h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading javax-activation-api
master00000|2022-05-18 13:57:15.940+0000 [id=114]	INFO	h.model.UpdateCenter$DownloadJob#run: Starting the installation of sshd on behalf of anonymous
master00000|2022-05-18 13:57:15.940+0000 [id=114]	INFO	h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading sshd
master00000|2022-05-18 13:57:16.037+0000 [id=114]	INFO	h.model.UpdateCenter$DownloadJob#run: Installation successful: sshd
master00000|2022-05-18 13:57:16.037+0000 [id=114]	INFO	h.model.UpdateCenter$DownloadJob#run: Starting the installation of jaxb on behalf of anonymous
master00000|2022-05-18 13:57:16.037+0000 [id=114]	INFO	h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading jaxb
master00000|2022-05-18 13:57:16.079+0000 [id=114]	SEVERE	h.model.UpdateCenter$DownloadJob#run: Failed to install jaxb
master00000|java.io.IOException: Failed to load: JAXB plugin (jaxb 2.3.6-1)
master00000| - Update required: JavaBeans Activation Framework (JAF) API (javax-activation-api 1.2.0-2) to be updated to 1.2.0-3 or higher
master00000|	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:994)
master00000|	at hudson.PluginManager.dynamicLoad(PluginManager.java:926)
master00000|Caused: java.io.IOException: Failed to install jaxb plugin
master00000|	at hudson.PluginManager.dynamicLoad(PluginManager.java:940)
master00000|	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2217)
master00000|Caused: java.io.IOException: Failed to dynamically deploy this plugin
master00000|	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2221)
master00000|	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1867)
master00000|	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
master00000|	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
master00000|	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
master00000|	at java.base/java.lang.Thread.run(Thread.java:829)
```

When using a LocalController we are already setting the flag to enable the form-path so we no longer need this plugin, so it can / should be skipped.  

not sure what can / should happen for other `Controllers`

### What Operating System are you using (both controller, and any agents involved in the problem)?

ci.jenkins.io - no idea if it is CentOs (stream) / Debian / Ubuntu / Amazon linux or whatever

### Reproduction steps

`mvn test -Dtest=OwnershipPluginTest`

### Expected Results

test passes

### Actual Results

test barfs

**Comment by jtnord** [comment]
was merged in #778
