### ISSUE TITLE
Master branch build broken down to UnsupportedClassVersionError expectations of dependencies

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/acceptance-test-harness#807]
While observing the stalled builds of the master branch, it appears the following test case fails, because core now requires Java 11 but something picks up Java 8 still:
https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/476/consoleFull

```
10:45:24  <===[JENKINS REMOTING CAPACITY]===>channel started
10:45:24  Jul 01, 2022 7:53:53 AM hudson.remoting.UserRequest perform
10:45:24  WARNING: LinkageError while performing UserRequest:hudson.slaves.SlaveComputer$SlaveVersion@730ead12
10:45:24  java.lang.UnsupportedClassVersionError: Failed to load hudson.slaves.SlaveComputer$SlaveVersion
10:45:24   at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:460)
10:45:24   at hudson.remoting.RemoteClassLoader.loadRemoteClass(RemoteClassLoader.java:292)
10:45:24   at hudson.remoting.RemoteClassLoader.loadWithMultiClassLoader(RemoteClassLoader.java:269)
10:45:24   at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:228)
10:45:24   at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
10:45:24   at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
10:45:24   at java.lang.Class.forName0(Native Method)
10:45:24   at java.lang.Class.forName(Class.java:348)
10:45:24   at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:132)
10:45:24   at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1986)
10:45:24   at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
10:45:24   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
10:45:24   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
10:45:24   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
10:45:24   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
10:45:24   at hudson.remoting.UserRequest.deserialize(UserRequest.java:289)
10:45:24   at hudson.remoting.UserRequest.perform(UserRequest.java:189)
10:45:24   at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:45:24   at hudson.remoting.Request$2.run(Request.java:376)
10:45:24   at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
10:45:24   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:45:24   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:45:24   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:45:24   at java.lang.Thread.run(Thread.java:748)
10:45:24  Caused by: java.lang.UnsupportedClassVersionError: hudson/slaves/SlaveComputer$SlaveVersion has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
10:45:24   at java.lang.ClassLoader.defineClass1(Native Method)
10:45:24   at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
10:45:24   at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
10:45:24   at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:458)
10:45:24   ... 23 more
```

**Comment by timja** [comment]
see https://github.com/jenkinsci/docker-fixtures/pull/38

**Comment by timja** [comment]
cool needs updating here too, I'll try do later on, (more than just bumping version, need to update some dockerfile hashes)
